#! /bin/sh
xrandr --output DP-2 --primary --mode 3840x2160 -r 160 --rotate normal --output DP-4 --mode 2560x1440 -r 165 --rotate normal --left-of DP-2
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/Pictures/Backgrounds/holo1.png &
picom -b --unredir-if-possible &
otd-daemon &
exec ~/scripts/polybar.sh &
dunst &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          5
bspc config top_padding 44 #Accounts for polybar having a height of 24px
bspc config bottom_padding 20
bspc config left_padding 20
bspc config right_padding 20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
